import {useEffect,useState} from 'react';
import {playerLines,type Intent} from '../../content';
import type {GameView,Action,Round} from '../../../server/engine';
import {roleOf} from '../../components/Scene';
import {MemberPortrait} from '../../components/MemberPortrait';
import {analyzeRound,signed} from './analysis';
import {SceneObject} from '../../ui/SceneObject';
import {OpenLedger} from '../../ui/OpenLedger';

export function Ledger({game:g}:{game:GameView}){return <><h3>本局记录</h3><div className="folio-score-line"><span>你 <b>{g.scores[0]}</b></span><span>{roleOf(g.opponent).name} <b>{g.scores[1]}</b></span></div><ol className="folio-history">{g.history.map(r=><li key={r.round}><span>第 {r.round} 轮 · {r.truth?'真签':'假签'}{r.inspected?'被查验':'被放行'}</span><b>{signed(r.delta[0])}</b></li>)}</ol>{!g.history.length&&<p>封签还未揭开。每轮的结果会记在这里。</p>}</>;}
export function DialogueBox({game:g}:{game:GameView}){return <SceneObject asset="note" label="桌边对话" className="conversation-note"><div className="note-inscription"><small>桌边对话</small><div className="conversation-scroll" aria-live="polite">{g.conversation.length?g.conversation.map((m,i)=><p key={`${g.round}-${i}`}><b>{m.who==='player'?'你':roleOf(g.opponent).name}：</b>{m.text}</p>):<p>{g.round===1?roleOf(g.opponent).intro:'轮到你了。我还没决定下一步。'}</p>}</div></div></SceneObject>;}
function ActionCard({title,english,detail,onClick,disabled=false,selected=false,asset='note'}:{title:string;english:string;detail:string;onClick:()=>void;disabled?:boolean;selected?:boolean;asset?:'note'|'true-seal'|'false-seal'}){return <SceneObject asset={asset} label={title} selected={selected} unavailable={disabled} onClick={onClick} className={`choice-note ${asset!=='note'?'seal-choice-note':''}`}><div className="note-inscription"><span className="choice-title"><b>{title}</b><small>{english}</small>{selected&&<em>已选</em>}</span><p>{detail}</p></div></SceneObject>;}
const talkOptions:[Intent|'silent',string,string][]=[['steady','陈述','STATE'],['challenge','质疑','CHALLENGE'],['friendly','商量','DISCUSS'],['silent','沉默','SILENCE']];
function Talks({game:g,busy,selected,onSelect}:{game:GameView;busy:boolean;selected:Intent|'silent'|null;onSelect:(intent:Intent|'silent')=>void}){return <div className="folio-choices talk-choices">{talkOptions.map(([intent,title,english])=><ActionCard key={intent} title={title} english={english} detail={intent==='silent'?(g.submitter==='player'?'不补充，让对方自己判断。':'不再试探，直接作决定。'):playerLines[g.role][g.submitter==='player'?'submit':'inspect'][intent]} disabled={busy} selected={selected===intent} onClick={()=>onSelect(intent)}/>)}</div>;}
function ScoreDocket({game:g,side}:{game:GameView;side:'player'|'opponent'}){const player=side==='player',id=player?g.role:g.opponent,index=player?0:1;return <SceneObject asset="note" label={player?'你的名帖':'电脑对手'} className="score-note"><div className="note-inscription"><div className="score-person"><MemberPortrait id={id} compact/><span><small>{player?'你的名帖':'电脑对手'}</small><strong>{roleOf(id).name}</strong></span></div><p className="score-numbers"><span>得分 <b>{g.scores[index]}</b></span><span>查验 <b>{g.checks[index]}/2</b></span></p></div></SceneObject>;}
export function SealGame({game:g,busy,act}:{game:GameView;busy:boolean;act:(a:Action)=>void;onRules:()=>void}){
 const [sealDraft,setSealDraft]=useState<boolean|null>(null),[talkDraft,setTalkDraft]=useState<Intent|'silent'|null>(null),[inspectDraft,setInspectDraft]=useState<boolean|null>(null);
 useEffect(()=>{setTalkDraft(null);setInspectDraft(null);},[g.phase,g.round]);
 const actionHint=g.phase==='choose'?'选一张签，确认后封口。':g.phase==='talk'?'说一句，或者把沉默留在桌上。':'对手已经封好。你可以放行，也可以拆开。';
 const canConfirm=g.phase==='choose'?sealDraft!==null:g.phase==='talk'?talkDraft!==null:inspectDraft!==null;
 const confirm=()=>{if(g.phase==='choose'&&sealDraft!==null)act({type:'seal',truth:sealDraft});else if(g.phase==='talk'&&talkDraft)act({type:'talk',intent:talkDraft});else if(g.phase==='inspect'&&inspectDraft!==null)act({type:'decide',inspect:inspectDraft});};
 const confirmLabel=busy?'请稍候…':g.phase==='choose'?sealDraft===null?'先取一张签':`封好${sealDraft?'真':'假'}签`:g.phase==='talk'?talkDraft===null?'先选一句':'递出便签':inspectDraft===null?'先作决定':inspectDraft?'拆开封签':'让它过去';
 return <main className={`club-stage3 object-scene folio-scene folio-play phase-${g.phase}`} aria-label="封签牌桌">
  <header className="folio-heading"><div><small>THE FIRST SEAL</small><h1>封签</h1></div><span className="folio-round">第 {g.round} 轮 / 8</span></header>
  <div className="game-paper-layout">
   <section className="folio-tableau" aria-label="桌上名帖与对话"><ScoreDocket game={g} side="player"/><DialogueBox game={g}/><ScoreDocket game={g} side="opponent"/></section>
   <section className="folio-turn" aria-label="当前行动" aria-busy={busy}>
    <header className="folio-action-heading"><h2>{g.phase==='choose'?'取一张签':g.phase==='talk'?'留一句话':'作出决定'}</h2><p>{actionHint}</p><small>{g.phase==='choose'?'尚未封口':g.submitter==='bot'?'对手封签 · 内容未揭晓':'封口完好'}</small></header>
    {g.phase==='choose'?<div className="folio-choices"><ActionCard asset="true-seal" title="真签" english="TRUE SEAL" detail="放行 +2 · 被查 +3" selected={sealDraft===true} onClick={()=>setSealDraft(true)} disabled={busy}/><ActionCard asset="false-seal" title="假签" english="FALSE SEAL" detail="放行 +4 · 被查 −3" selected={sealDraft===false} onClick={()=>setSealDraft(false)} disabled={busy}/></div>:g.phase==='talk'?<Talks game={g} busy={busy} selected={talkDraft} onSelect={setTalkDraft}/>:<><div className="folio-choices"><ActionCard title="放行" english="LET IT PASS" detail="保留查验次数" selected={inspectDraft===false} onClick={()=>setInspectDraft(false)} disabled={busy}/><ActionCard title="拆封" english="BREAK THE SEAL" detail={g.checks[0]?`消耗 1 次 · 剩余 ${g.checks[0]}`:'查验次数已用完'} selected={inspectDraft===true} onClick={()=>setInspectDraft(true)} disabled={busy||g.checks[0]===0}/></div>{!g.talked&&<div className="folio-talk-inline"><span>想先试探一句？</span>{(['steady','challenge','friendly'] as Intent[]).map((intent,i)=><button key={intent} disabled={busy} onClick={()=>act({type:'talk',intent})}>{['陈述','质疑','商量'][i]}</button>)}</div>}</>}
   </section>
   <footer className="folio-confirm"><small>01 取签 · 02 对话与决定 · 03 揭封</small><SceneObject asset="note" label={confirmLabel} onClick={confirm} unavailable={busy||!canConfirm} className="confirm-note"><div className="note-inscription"><b>{confirmLabel}</b></div></SceneObject></footer>
  </div>
 </main>;
}
export function RoundReview({round:r}:{round:Round}){const a=analyzeRound(r);return <><h3>如果换一个决定</h3><p>{a.canSwitch?`保持此签不变，若${r.inspected?'放行':'查验'}，本轮你得 ${signed(a.alternative)} 分。`:'查验次数当时已经用完，这一轮没有查验的选项。'}</p><p className="ink-note">这是揭晓后的比较，不代表当时一定应该这样选。</p></>;}
export function Reveal({game:g,busy,onNext,onLearn,onAgain}:{game:GameView;busy:boolean;onNext:()=>void;onLearn:()=>void;onAgain:()=>void}){
 const [round,setRound]=useState(g.history.length),[expanded,setExpanded]=useState(g.learning),[view,setView]=useState<'analysis'|'cost'|'record'>('analysis');
 const ended=g.phase==='ended',r=g.history[(ended?round:g.history.length)-1],a=analyzeRound(r);
 const winner=g.scores[0]===g.scores[1]?'平局':g.scores[0]>g.scores[1]?'你赢了':`${roleOf(g.opponent).name}赢了`;
 return <main className="club-stage3 object-scene folio-scene folio-reveal" aria-label="揭封与复盘">
  <header className="folio-heading"><div><small>{ended?'CASE CLOSED':'REVEAL & ANALYSIS'}</small><h1>{ended?winner:'揭封与复盘'}</h1></div><span>{ended?`最终比分 ${g.scores[0]} : ${g.scores[1]}`:`第 ${r.round} 轮 / 8`}</span></header>
  <OpenLedger labels={['揭封结果','复盘分析']} left={<><small>{ended?'本局结束':'本轮揭封'}</small><h2>{r.truth?'真签':'假签'} · {r.inspected?'被查验':'被放行'}</h2><div className="leaf-scroll"><p>{a.explanation}</p><div className="folio-score-line"><span>你 <b>{signed(ended?g.scores[0]:r.delta[0])}</b></span><span>{roleOf(g.opponent).name} <b>{signed(ended?g.scores[1]:r.delta[1])}</b></span></div>{ended&&<p>“{g.conversation.at(-1)?.text}”</p>}<p>剩余查验：你 {g.checks[0]} / 2，{roleOf(g.opponent).name} {g.checks[1]} / 2。</p></div>{ended&&<nav className="folio-round-tabs" aria-label="选择复盘轮次">{g.history.map(h=><button key={h.round} aria-pressed={round===h.round} onClick={()=>setRound(h.round)}>{h.round}</button>)}</nav>}</>} right={<><nav className="folio-analysis-tabs" aria-label="卷宗内容"><button aria-pressed={view==='analysis'} onClick={()=>setView('analysis')}>复盘分析</button><button aria-pressed={view==='cost'} onClick={()=>setView('cost')}>查验代价</button><button aria-pressed={view==='record'} onClick={()=>setView('record')}>本局记录</button></nav><div className={`leaf-scroll review-${view}`}>{view==='record'?<Ledger game={g}/>:view==='cost'?<><h3>查验的代价</h3><p>{a.resource}</p><details><summary>查看这一轮的对话</summary>{r.conversation.length?r.conversation.map((m,i)=><p key={i}><b>{m.who==='player'?'你':roleOf(g.opponent).name}：</b>{m.text}</p>):<p>这一轮没有对话记录。</p>}</details><p className="ink-note">这里解释实际得分与取舍，不推测对手没有表露的心理活动。</p></>:expanded||ended?<RoundReview round={r}/>:<><p>你可以先看结果，也可以展开这一轮的得分解释。</p><button className="paper-link" onClick={()=>setExpanded(true)}>展开本轮分析</button></>}</div></>}/>
  <footer className="folio-reveal-actions"><SceneObject asset="note" label={ended?'再玩一局':g.round===8?'查看本局结果':'下一轮'} onClick={ended?onAgain:onNext} unavailable={busy} className="confirm-note"><div className="note-inscription"><b>{ended?'再玩一局':g.round===8?'查看本局结果':'下一轮'}</b></div></SceneObject><SceneObject asset="note" label="博弈原理" onClick={onLearn} className="confirm-note"><div className="note-inscription"><b>博弈原理</b></div></SceneObject></footer>
 </main>;
}

